services:
  db:
    image: postgres:14-alpine 
    container_name: fox_paper_db
    restart: always
    volumes: 
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fox_paper
    networks:
      - fox_paper_network

  app:
    build: . 
    container_name: fox_paper
    image: fox_paper_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@172.22.0.2:5432/fox_paper
    networks:
      - fox_paper_network

networks:
  fox_paper_network:
    driver: bridge

volumes:
  postgres_data: 
