services:
  db:
    image: postgres:14-alpine 
    container_name: fox_paper_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  web:
    build: . 
    container_name: fox_paper_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: 5432
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}