services:
  db:
    image: postgres:14-alpine 
    container_name: fox_paper_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pa55word
      POSTGRES_DB: fox_paper

  web:
    build: . 
    container_name: fox_paper_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:pa55word@db:5432/fox_paper
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
