[build]
command = "apt-get update && apt-get install -y python3.8-venv && python3.8 -m venv venv && source venv/bin/activate && pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8080"
