"""remove is_published

Revision ID: 8830092f5226
Revises: d8172dd06200
Create Date: 2024-04-23 12:14:24.484449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8830092f5226'
down_revision: Union[str, None] = 'd8172dd06200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researches', 'is_published')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researches', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
