"""add research_categories

Revision ID: 5d6aa3ed035a
Revises: e8215336e53b
Create Date: 2024-04-13 17:36:11.912551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6aa3ed035a'
down_revision: Union[str, None] = 'e8215336e53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_categories',
    sa.Column('research_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['research_id'], ['researches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('research_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_categories')
    # ### end Alembic commands ###
