"""file

Revision ID: bbc5f60b89d2
Revises: 5d6aa3ed035a
Create Date: 2024-04-13 20:30:01.105564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc5f60b89d2'
down_revision: Union[str, None] = '5d6aa3ed035a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'files', ['file_path'])
    op.drop_column('files', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'files', type_='unique')
    # ### end Alembic commands ###
