"""add unique to researches.file_id

Revision ID: cbc72a6d02c1
Revises: b38bed1858c8
Create Date: 2024-04-13 17:08:09.360651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc72a6d02c1'
down_revision: Union[str, None] = 'b38bed1858c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'researches', ['file_id'])
    op.drop_constraint('researches_file_id_fkey', 'researches', type_='foreignkey')
    op.create_foreign_key(None, 'researches', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'researches', type_='foreignkey')
    op.create_foreign_key('researches_file_id_fkey', 'researches', 'files', ['file_id'], ['id'])
    op.drop_constraint(None, 'researches', type_='unique')
    # ### end Alembic commands ###
