"""remove research_authors

Revision ID: e8215336e53b
Revises: cbc72a6d02c1
Create Date: 2024-04-13 17:26:01.118402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8215336e53b'
down_revision: Union[str, None] = 'cbc72a6d02c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_categories')
    op.add_column('researches', sa.Column('author_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researches', 'author_id')
    op.create_table('research_categories',
    sa.Column('research_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='research_categories_category_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['research_id'], ['researches.id'], name='research_categories_research_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('research_id', 'category_id', name='research_categories_pkey')
    )
    # ### end Alembic commands ###
